apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: bi1982s9z-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/bi1982s9z-java-quarkus-gitops